# Generated by Django 4.2.7 on 2023-11-23 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_products_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_slug',
            field=models.SlugField(default='asdsa', unique=True, verbose_name='Product Slug'),
            preserve_default=False,
        ),
    ]
