# Generated by Django 4.2.7 on 2023-11-23 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_products_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='product_slug',
        ),
    ]
