# Generated by Django 4.2.7 on 2023-11-23 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_products_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_slug',
            field=models.SlugField(blank=True, verbose_name='Product Slug'),
        ),
    ]
