# Generated by Django 4.2.7 on 2023-11-29 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_product_rating_post_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='post',
            new_name='product',
        ),
    ]
